export const allSuggestions = [
    { display: "성산일출봉", text: "성산일출봉이 붐비는지 궁금해" },
    { display: "한라산", text: "한라산이 붐비는지 알아봐줘" },
    { display: "섭지코지", text: "섭지코지가 붐비는지 알고싶어" },
    { display: "우도", text: "우도가 붐비는지 궁금해" },
    { display: "협재해수욕장", text: "협재해수욕장이 붐비는지 알아봐줘" },
    { display: "함덕해수욕장", text: "함덕해수욕장이 붐비는지 알고싶어" },
    { display: "카멜리아힐", text: "카멜리아힐이 붐비는지 궁금해" },
    { display: "휴애리자연생활공원", text: "휴애리자연생활공원이 붐비는지 알아봐줘" },
    { display: "정방폭포", text: "정방폭포가 붐비는지 알고싶어" },
    { display: "천제연폭포", text: "천제연폭포가 붐비는지 궁금해" },
    { display: "천지연폭포", text: "천지연폭포가 붐비는지 알아봐줘" },
    { display: "쇠소깍", text: "쇠소깍이 붐비는지 알고싶어" },
    { display: "만장굴", text: "만장굴이 붐비는지 궁금해" },
    { display: "비자림", text: "비자림이 붐비는지 알아봐줘" },
    { display: "산굼부리", text: "산굼부리가 붐비는지 알고싶어" },
    { display: "한림공원", text: "한림공원이 붐비는지 궁금해" },
    { display: "제주절물자연휴양림", text: "제주절물자연휴양림이 붐비는지 알아봐줘" },
    { display: "에코랜드", text: "에코랜드가 붐비는지 알고싶어" },
    { display: "용두암", text: "용두암이 붐비는지 궁금해" },
    { display: "스누피가든", text: "스누피가든이 붐비는지 알아봐줘" },
];
